(ns marchio.chars)

(def Tab          (char  9))
(def Newline      (char 10))
(def Space        (char 32))
(def Bang         (char 33))
(def Doublequote  (char 34))
(def Ampersand    (char 38))
(def Singlequote  (char 39))
(def OpenParen    (char 40))
(def CloseParen   (char 41))
(def Asterisk     (char 42))
(def Colon        (char 58))
(def LessThan     (char 60))
(def GreaterThan  (char 62))
(def OpenBracket  (char 91))
(def Backslash    (char 92))
(def CloseBracket (char 93))
(def Underscore   (char 95))
(def Underscore   (char 95))
(def Backtick     (char 96))