(ns marchio.chars)

(def Asterisk     (char 42))
(def Underscore   (char 95))
(def Newline      (char 10))
(def Underscore   (char 95))
(def Backtick     (char 96))
(def OpenBracket  (char 91))
(def CloseBracket (char 93))
(def LessThan     (char 60))
(def Bang         (char 33))
(def Backslash    (char 92))
(def Ampersand    (char 38))
(def OpenParen    (char 40))
(def CloseParen   (char 41))
(def Colon        (char 58))
(def Singlequote  (char 39))
(def Doublequote  (char 34))